# variable 

Variable is an identifer used to store a value in program.

variables allows us to store different type of data, such letters,numbers and special charcters.

## variables rules:
-We can use letters,numbesr and underscore('_') in variables names.

-A variable name must start with letters or underscore(_)

-Variable name cannot start with numbers

-python is case-sensetive, so 'name' and 'Name' are different variables.

## step 2 - Demostrate the concept

variables 
name="dhinesh"

`name` is a variable and `"dhinesh"` is a value stored in the variable.

number=10

`number` is a variable and `10` is a value stored in the variable.
   

In [2]:
name="dhinesh" 
age=23
height=5.4
city="salem"

print("Name:",name)
print("Age:",age)
print("Height:",height)
print("City:",city)

Name: dhinesh
Age: 23
Height: 5.4
City: salem


## Code Explanation

In this program, I created four variables: `name`, `age`, `height`, and `city`.

The `name` and `city` variables store string values.

The `age` variable stores an integer value, and the `height` variable stores a float value.

I used the `print()` function to display all the variable values in the console.

# Data Types

A data type tells Python what type of value is stored in a variable.

Python has different built-in data types for storing different kinds of data.

## Common Python Data Types

- `int` – used to store whole numbers.

- `float` – used to store decimal numbers.

- `str` – used to store text. A string can be enclosed within single quotes (`' '`) or double quotes (`" "`).

- `bool` – used to store `True` or `False` values.

In [3]:
name="dhineshkumar"
age=22
height=5.5
is_employee=True
print(name,type(name))
print(age,type(age))
print(height,type(height))
print(is_employee,type(is_employee))

dhineshkumar <class 'str'>
22 <class 'int'>
5.5 <class 'float'>
True <class 'bool'>


## Code Explanation

In this program, I created four variables: `name`, `age`, `height`, and `is_employee`.

- The `name` variable stores a string value.
- The `age` variable stores an integer value.
- The `height` variable stores a decimal value.
- The `is_employee` variable stores a Boolean value.

I used two functions: `print()` and `type()`.

- The `print()` function displays the values in the console.
- The `type()` function tells us the data type of a value.

# Type Casting

Type casting means converting a value from one data type to another data type

## Type casting built-in function

`int()`- converts a value into an integer.

`float()`- converts a value into a floating-point number

`bool()`- converts a value into a boolean values

`str()` - converts a value into a string value.`

# Step 2 – Demonstrate the Concept

## Real-World Example

Suppose a student gets a mark of `89.5`.

The mark is stored as a float because it contains a decimal value.

If the system requires a whole-number mark, we can convert the float value into an integer using `int()`.

For example:

89.5 → 89


name="dhinesh"
age=24
float_mark=89.5

#folat to integer
int_mark=int(float_mark)

#integer to float
float_age=float(age)

#integer to string
str_age=str(age)

print("original values")
print(name,type(name))
print(age,type(age))
print(float_mark,type(float_mark))

print("\nconvert values")

print(int_mark,type(int_mark))
print(float_age,type(float_age))
print(str_age,type(str_age))



In [15]:
name="dhinesh"
age=24
float_mark=89.5

#folat to integer
int_mark=int(float_mark)

#integer to float
float_age=float(age)

#integer to string
str_age=str(age)

print("original values")
print(name,type(name))
print(age,type(age))
print(float_mark,type(float_mark))

print("\nconvert values")

print(int_mark,type(int_mark))
print(float_age,type(float_age))
print(str_age,type(str_age))



original values
dhinesh <class 'str'>
24 <class 'int'>
89.5 <class 'float'>

convert values
89 <class 'int'>
24.0 <class 'float'>
24 <class 'str'>


## Code Explanation

In this program, I created three variables with different values.

I converted the float value `89.5` into an integer using `int()`.

I converted the integer value `24` into a float using `float()`.

I converted the integer value `24` into a string using `str()`.

I used the `print()` function to display the values and the `type()` function to check their data types.


# Operators

Operators is a symbols or keywords used to perform operations on value and variabes

## Types of Operators

- Arithmetic Operators
- Assignment Operators
- Comparison Operators
- Logical Operators

### Arithmetic Operators

Arithmetic operators are used to perform mathematical operations.

Examples: `+`, `-`, `*`, `/`, `%`, `//`, `**`

### Assignment Operators

Assignment operators are used to assign or update values in variables.

Examples: `=`, `+=`, `-=`, `*=`, `/=`

### Comparison Operators

Comparison operators are used to compare two values.

Examples: `==`, `!=`, `>`, `<`, `>=`, `<=`

### Logical Operators

Logical operators are used to combine or evaluate conditions.

Examples: `and`, `or`, `not`



In [1]:
# Student marks
python_mark=60
sql_mark=80
math_mark=90

# Calculate total marks
total=python_mark+sql_mark+math_mark

# Calculate average marks
average=total/3

# Passing average
passing_mark=50

# Check pass or fail
is_pass=average>=passing_mark

# Display the results
print("Python Mark:",python_mark)
print("SQL Mark:",sql_mark)
print("Math Mark:",math_mark)

print("Total Marks:",total)
print("Average Marks:",average)
print("Pass:",is_pass)

if is_pass:
    print("Result: Pass")
else:
    print("Result: Fail")


Python Mark: 60
SQL Mark: 80
Math Mark: 90
Total Marks: 230
Average Marks: 76.66666666666667
Pass: True
Result: Pass


# Input

-Information or data provided to a Python program by the user.

input()

    The input() function is used to get data from the user.

In [2]:
name=input("Enter your name:")
age=input("Enter your age:")

print("Name:",name)
print("Age:",age)

Enter your name: dhineshkumar
Enter your age: 22


Name: dhineshkumar
Age: 22


# Output

-Output is the information or data produced by a Python program and displayed on the console.

print()

    The print() function is used to display values on the console.

In [3]:
name="dhineshkumar"
age=22
city="salem"
print("Name:",name)
print("age:",age)

Name: dhineshkumar
age: 22


# Comments

-Comments are notes written in a Python program to explain the code. Python does not execute comments.

Comments Types

    Single-line comments
    Multi-line comments


In [4]:
# This is a Single-line comment
print("Hello")

# This is a multi-line comment
address="""
30,Tharamangalam
omalur,
salem-646401"""
print(address)



Hello

30,Tharamangalam
omalur,
salem-646401


# Control Flow

## if / elif / else

### if

-if checks a condition. If it is true, the code inside if runs.

### elif

-elif checks another condition when the previous condition is false.

### else

else runs when all the previous conditions are false.

In [6]:
age = 16

if age >= 18:
    print("Eligible to vote")
elif age >= 13:
    print("Teenager - Not eligible to vote")
else:
    print("Child - Not eligible to vote")

Teenager - Not eligible to vote


# For Loop

A for loop is used to repeat a block of code for each item in a sequence.

In [7]:
#Print numbers from 1 to 5.

for number in range(1, 6):
    print(number)

1
2
3
4
5


# While Loop

A while loop repeatedly executes a block of code as long as the condition is true.

In [8]:
count=1

while count<= 5:
    print(count)
    count+=1

1
2
3
4
5


# break

The break statement immediately stops the loop and exits it.


In [9]:
for i in range(1,6):
    if i==3:
        break
    print(i)

1
2


# Continue

The continue statement skips the current iteration and moves to the next iteration.

In [10]:
for i in range(1,6):
    if i==4:
        continue
    print(i)

1
2
3
5


# Pass

The pass statement does nothing. It acts as a placeholder.

In [11]:
for i in range(1,6):
    if i==3:
        pass
    print(i)

1
2
3
4
5


# Collections

## List

-Lists are used to store multiple items in a single variable.

-List items are ordered and allow duplicate values.

-List items are indexed, the first item has index [0], the second item has index [1] etc.

-Lists are mutable, so we can change their values.

-Lists are created using square brackets [].

## Real-time example:

In an online shopping application, a customer's selected products can be stored in a list.

["Laptop","Mouse","Keyboard"]

In [12]:
products=["Laptop","Mouse","Keyboard","Mouse"]

print(products)
print(products[0])

products[1]="Monitor"
print(products)

['Laptop', 'Mouse', 'Keyboard', 'Mouse']
Laptop
['Laptop', 'Monitor', 'Keyboard', 'Mouse']


# Tuple

-Tuples are used to store multiple items in a single variable

-Tuples are immutable, so their values cannot be changed after creation.

-Tuples allow duplicate values

-Tuples can store different data types.

-Tuples are usually created using parentheses ()

## Real-time example:

A company's employee ID details can be stored in a tuple because the stored information should not be changed.

(101,"Dhinesh","AI/ML Engineer")

In [17]:
employee=(101,"Dhinesh","AI/ML Engineer")

print(employee)
print(employee[1])


(101, 'Dhinesh', 'AI/ML Engineer')
Dhinesh


## Step 1 – Understand the Concept

### Set

A set is a collection used to store unique values. Sets are unordered and mutable, so items can be added or removed.

-Sets do not allow duplicate values

-Set items are not accessed using index numbers.

-A set can contain different data types.

-Sets are created using curly brackets {}.

## Step-2 Demonstrate the Concept

Think of a college attendance system. If the same student is marked present twice, we need to keep the student only once.

101,102,101,103

A set stores only the unique student IDs:

101,102,103


In [18]:
student_ids={101,102,101,103}

print(student_ids)

student_ids.add(104)

print(student_ids)

{101, 102, 103}
{104, 101, 102, 103}


### Explanation

student_ids is a set.

The duplicate value 101 is automatically removed.

add() adds a new value to the set.

This demonstrates that sets store unique values and can be changed.

## Step 1 – Understand the Concept

### Dictionary

Dictionaries are used to store data values in key:value pairs.

-Each key identifies a value

-Keys must be unique.

-Dictionaries are mutable, so values can be changed.

-A dictionary is created using curly brackets {}

## Step-2 Demonstrate the Concept

The student record. A student has different details such as name, age, and course.

Name → Dhinesh

Age → 21

Course → Python

## Implementation & Explanation

In [19]:
student={
    "name":"Dhinesh",
    "age":21,
    "course":"Python"
}

print(student["name"])

student["age"]=22

print(student)

Dhinesh
{'name': 'Dhinesh', 'age': 22, 'course': 'Python'}


## Step 1 – Understand the Concept

### List Comprehension

List comprehension is a short way to create a new list from an existing sequence.

## Step-2 Demonstrate the Concept

shopping application. Suppose we have product prices and want to create a new list containing only prices above ₹500.

100, 750, 300, 1200

The new list will contain:

750, 1200

## Implementation & Explanation


In [20]:
prices=[100,750,300,1200]

expensive=[price for price in prices if price>500]

print(expensive)

[750, 1200]


-for price in prices checks each price.

-if price>500 selects prices above 500.

-The selected values are stored in the new list expensive.

-print the expensive

## Step 1 – Understand the Concept

### Dictionary Comprehension

Dictionary comprehension is a short and simple way to create a new dictionary using a loop.

Normally, we use a for loop to create a dictionary. With dictionary comprehension, we can do the same thing in a single line.

## Step 2 – Demonstrate the Concept

We have two list of students and their marks

students=["Arun","Bala","Dhinesh"]

marks=[80,75,90]

We want to create a dictionary like:

{

    "Arun":80,
    
    "Bala":75,
    
    "Dhinesh":90
    
}


In [22]:
students=["Arun","Bala","Dhinesh"]
marks=[80,75,90]

student_marks={student:mark for student,mark in zip(students,marks)}

print(student_marks)

{'Arun': 80, 'Bala': 75, 'Dhinesh': 90}


-student → becomes the key

-mark → becomes the value

-for student,mark → takes each pair

-zip(students,marks) → connects the two lists

## Step 1 – Understand the Concept

### Function Definition

A function is a block of code that is used to perform a specific task.

A function is created using the def keyword. The code inside the function is executed when we call the function.


In [25]:
def welcome():
    print("Welcome to Python")

welcome()

Welcome to Python


### Arguments

Arguments

Arguments are the values that we pass to a function when we call the function.

Arguments are used to give input to the function

In [26]:
def greet(name):
    print("Hello",name)

greet("Dhinesh")

Hello Dhinesh


### Default Arguments

A default argument is a value that is already assigned to a parameter in the function definition

If we do not pass a value when calling the function, Python uses the default value.

In [28]:
def greet(name="Dhinesh"):
    print("Hello",name)

greet()
greet("Varun")

Hello Dhinesh
Hello Varun


### Keyword Arguments

Keyword arguments are arguments that are passed to a function using the parameter name.

Instead of passing values only by their position, we specify which parameter should receive each value.

In [29]:
def student(name,age):
    print(name,age)

student(name="Dhinesh",age=21)

Dhinesh 21


### Variable-Length Arguments (*args, **kwargs)

Variable-length arguments are used when we don't know how many arguments will be passed to a function.

-*args 

    *args is used when we want to pass any number of positional arguments.

-**kwargs 

    **kwargs is used when we want to pass any number of keyword arguments.

In [34]:
#*args

def add_numbers(*numbers):
    total=0

    for number in numbers:
        total=total+number

    print("Total:",total)

add_numbers(10,20)
add_numbers(10,20,30)

print()

def student_details(**details):
    print(details)

student_details(name="Dhinesh",age=21,course="Python")


Total: 30
Total: 60

{'name': 'Dhinesh', 'age': 21, 'course': 'Python'}


## Step 1 – Understand the Concept

### Lambda Functions

-A lambda function is a small anonymous function.

-A lambda function can take any number of arguments, but can only have one expression.

## Step 2 – Demonstrate the Concept

Suppose an application needs to double a number.

In [35]:
square=lambda number:number*number

print(square(5))

25


## Step 1 – Understand the Concept

-A recursive function is a function that calls itself to solve a problem.

-The function keeps calling itself with a smaller or simpler value until it reaches a stopping condition, called the base condition

-Recursive call → the function calls itself.

-Base condition → tells the function when to stop.

Real-time example: Countdown

Suppose we want to count down from 5:

In [36]:
def countdown(number):
    if number==0:
        return

    print(number)
    countdown(number-1)

countdown(5)

5
4
3
2
1


# Advanced Python

## iterator

An iterator is an object that allows you to access elements one by one from a collection or sequence.

-iter() → creates an iterator from an iterable.

-next() → gets the next value from the iterator.


Real-time example:

-Imagine a queue at a ticket counter:

Person 1 → Person 2 → Person 3 → Person 4

In [37]:
numbers=[10,20,30,40]

number_iterator=iter(numbers)

print(next(number_iterator))
print(next(number_iterator))
print(next(number_iterator))
print(next(number_iterator))

10
20
30
40


## Generators

A generator is a special type of function that produces values one at a time instead of producing all values at once.

Generators use the yield keyword.

Real-time example:

Imagine an application has 1 lakh customer records.

Instead of loading all 1 lakh records into memory:


In [39]:
def numbers():
    yield 1
    yield 2
    yield 3

result=numbers()

print(next(result))
print(next(result))


1
2


### yield

yield is a Python keyword used in a generator function.

It is used to produce one value at a time and pause the function.

### Demonstrate the Concept

Think of a vending machine:

Request → 1 item → pause
Request → 1 item → pause
Request → 1 item → pause


In [41]:
def numbers():
    yield 10
    yield 20
    yield 30

result=numbers()

print(next(result))
print(next(result))
print(next(result))

10
20
30


### Decorators

A decorator is a function that is used to add extra functionality to another function without changing the original function's code.

Real-time example:

Imagine you have a basic mobile phone.

Basic Phone
    ↓
Add Camera
    ↓
Add extra feature

In [43]:
def decorator(function):
    def wrapper():
        print("Before")
        function()
        print("After")
    return wrapper

@decorator
def hello():
    print("Hello")

hello()

Before
Hello
After


### Closures

A closure is a function that remembers and uses a value from its outer function even after the outer function has finished running.


In [44]:
def create_greeting(name):
    def greeting():
        print("Hello",name)
    return greeting

hello=create_greeting("Dhinesh")

hello()

Hello Dhinesh


### global

global is used inside a function when we want to change a variable that belongs to the global scope

In [45]:
count=0

def increase():
    global count
    count=count+1

increase()

print(count)

1


### nonlocal

nonlocal is used inside a nested function when we want to change a variable that belongs to the outer function.


In [46]:
def counter():
    count=0

    def increase():
        nonlocal count
        count=count+1
        print(count)

    increase()
    increase()

counter()

1
2
